export const TYPES = {
  REQUEST_FETCH_PRICES: 'REQUEST_FETCH_PRICES',
  SUCCESS_FETCH_PRICES: 'SUCCESS_FETCH_PRICES',
  FAILURE_FETCH_PRICES: 'FAILURE_FETCH_PRICES',

  REQUEST_FETCH_ORDERS: 'REQUEST_FETCH_ORDERS',
  SUCCESS_FETCH_ORDERS: 'SUCCESS_FETCH_ORDERS',
  FAILURE_FETCH_ORDERS: 'FAILURE_FETCH_ORDERS',

  REQUEST_SAVE_ORDER: 'REQUEST_SAVE_ORDER',
  SUCCESS_SAVE_ORDER: 'SUCCESS_SAVE_ORDER',
  FAILURE_SAVE_ORDER: 'FAILURE_SAVE_ORDER',

  CHANGE_BASE: 'CHANGE_BASE',
};
