export const TYPES = {
  REQUEST_FETCH_PRICES: 'REQUEST_FETCH_PRICES',
  SUCCESS_FETCH_PRICES: 'SUCCESS_FETCH_PRICES',
  FAILURE_FETCH_PRICES: 'FAILURE_FETCH_PRICES',
  CHANGE_BASE: 'CHANGE_BASE',
};
