export const TYPES = {
  REQUEST_FETCH_HOURLY_PRICES: 'REQUEST_FETCH_HOURLY_PRICES',
  SUCCESS_FETCH_HOURLY_PRICES: 'SUCCESS_FETCH_HOURLY_PRICES',
  FAILURE_FETCH_HOURLY_PRICES: 'FAILURE_FETCH_HOURLY_PRICES',

  REQUEST_FETCH_PRICES: 'REQUEST_FETCH_PRICES',
  SUCCESS_FETCH_PRICES: 'SUCCESS_FETCH_PRICES',
  FAILURE_FETCH_PRICES: 'FAILURE_FETCH_PRICES',

  REQUEST_FETCH_ORDERS: 'REQUEST_FETCH_ORDERS',
  SUCCESS_FETCH_ORDERS: 'SUCCESS_FETCH_ORDERS',
  FAILURE_FETCH_ORDERS: 'FAILURE_FETCH_ORDERS',

  REQUEST_SAVE_ORDER: 'REQUEST_SAVE_ORDER',
  SUCCESS_SAVE_ORDER: 'SUCCESS_SAVE_ORDER',
  FAILURE_SAVE_ORDER: 'FAILURE_SAVE_ORDER',

  CHANGE_BASE: 'CHANGE_BASE',

  REQUEST_SAVE_TOKEN: 'REQUEST_SAVE_TOKEN',
  SUCCESS_SAVE_TOKEN: 'SUCCESS_SAVE_TOKEN',
  FAILURE_SAVE_TOKEN: 'FAILURE_SAVE_TOKEN',
};

export const VIEWS = {
  HOURLY: 'hour',
};
